return {
	title = "LrGeniusAI",
	id = "lrgeniusTagset",
	items = {
		"com.adobe.filename",
		"com.adobe.copyname",
		"com.adobe.folder",
		"com.adobe.dateTimeOriginal",
		"com.adobe.rating",
		"com.adobe.colorLabels",
		"com.adobe.GPS",
		"com.adobe.exposure",
		"com.adobe.exposureProgram",
		"com.adobe.exposureBiasValue",
		"com.adobe.focalLength",
		"com.adobe.isoSpeed",
		"com.adobe.lensModel",
		"com.adobe.model",
		"com.adobe.separator",
		"com.adobe.title",
		{ "com.adobe.caption", height_in_lines = 5 },
		{ "com.adobe.altTextAccessibility", height_in_lines = 5 },
		"com.adobe.separator",
		_PLUGIN.id .. ".aiModel",
		_PLUGIN.id .. ".aiLastRun",
		_PLUGIN.id .. ".aiEditModel",
		_PLUGIN.id .. ".aiEditLastRun",
		_PLUGIN.id .. ".aiEditStatus",
		{ _PLUGIN.id .. ".aiEditSummary", height_in_lines = 4 },
		{ _PLUGIN.id .. ".aiEditWarnings", height_in_lines = 4 },
		_PLUGIN.id .. ".cullDecision",
		_PLUGIN.id .. ".cullScore",
		_PLUGIN.id .. ".cullGroupType",
		_PLUGIN.id .. ".cullGroupId",
		_PLUGIN.id .. ".cullGroupRank",
		_PLUGIN.id .. ".cullGroupWinner",
		_PLUGIN.id .. ".cullTechnicalScore",
		_PLUGIN.id .. ".cullSharpness",
		_PLUGIN.id .. ".cullExposure",
		_PLUGIN.id .. ".cullNoise",
		_PLUGIN.id .. ".cullFaceCount",
		_PLUGIN.id .. ".cullAesthetic",
		_PLUGIN.id .. ".cullFaceSharpness",
		_PLUGIN.id .. ".cullFaceProminence",
		_PLUGIN.id .. ".cullFaceVisibility",
		_PLUGIN.id .. ".cullFaceScore",
		_PLUGIN.id .. ".cullOcclusion",
		_PLUGIN.id .. ".cullEyeOpenness",
		_PLUGIN.id .. ".cullBlinkPenalty",
		{ _PLUGIN.id .. ".cullReasonCodes", height_in_lines = 2 },
		{ _PLUGIN.id .. ".cullExplanation", height_in_lines = 4 },
		{ _PLUGIN.id .. ".photoContext", height_in_lines = 5 },
	},
}
